name       : guayadeque
version    : 0.4.6
release    : 7
source     :
    - git|https://github.com/anonbeat/guayadeque.git : 4eacc22eda1c307844d0aec9ff5782a881225d99
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Guayadeque Music Player
description: |
    Guayadeque Music Player
builddeps  :
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(wxsqlite3)
    - wxwidgets-devel
rundeps    :
    - gtk2-engine-murrine
setup      : |
    %patch -p1 < $pkgfiles/wx-config.patch
    %cmake_ninja 
build      : |
    %ninja_build
install    : |
    %ninja_install
