name       : guayadeque
version    : 0.4.6
release    : 6
source     :
    - https://github.com/anonbeat/guayadeque/archive/v0.4.6.tar.gz : 3c0d782c6f4aa511c7a635a78742542d130d1a13e20648db886ccfce4e1b9d4f
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Guayadeque Music Player
description: |
    Guayadeque Music Player
builddeps  :
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libcurl)
    - pkgconfig(libgpod-1.0)
    - pkgconfig(sqlite3)
    - pkgconfig(taglib)
    - pkgconfig(wxsqlite3)
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/wx-components.patch
    %cmake -DCMAKE_INSTALL_PREFIX=/usr .
build      : |
    %make
install    : |
    %make_install
